config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles
  post '/articles/new' , to: 'articles#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def show
    @articles = Article.find(params[:id])
  end
  def new
    @articles = Article.new
  end
  def create
    @articles = Article.new(title: params[:title],body: params[:body])
    # play ssti ?
    if @articles.save
      redirect_to @articles
    else
      render :new
    end
  end
  def destroy
    @articles = Article.find(params[:id])
    @articles.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
      <iframe srcdoc="<p><%= article.body.html_safe %></p>">
      </iframe>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <br/>
    <%= form.label :body %>
    <%= form.text_area :body %>
    <br/>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "back", root_path %>

app/views/articles/show.html.erb
<h1><%= @articles.title.html_safe %></h1>
<p> <%= @articles.body %></p>

<%= link_to "back",root_path %>

<%= link_to "delete", article_path(@articles),
           method: :delete,
           data: { confirm: "delete it" }
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>